version: '1.0'
services:
  app:
    image: node:14
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: "production"
        APP_VERSION: "1.0.0"
    run:
      cmd: ["npm", "start"]
      port: 3000
    environment:
      NODE_ENV: "production"
      APP_VERSION: "1.0.0"
